// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package go_grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SimpleGrpcServerServicesClient is the client API for SimpleGrpcServerServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleGrpcServerServicesClient interface {
	//Check if 'gRPC-server' is alive with this service
	AreYouAlive(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type simpleGrpcServerServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleGrpcServerServicesClient(cc grpc.ClientConnInterface) SimpleGrpcServerServicesClient {
	return &simpleGrpcServerServicesClient{cc}
}

func (c *simpleGrpcServerServicesClient) AreYouAlive(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/simpleGrpcServer.SimpleGrpcServerServices/AreYouAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleGrpcServerServicesServer is the server API for SimpleGrpcServerServices service.
// All implementations must embed UnimplementedSimpleGrpcServerServicesServer
// for forward compatibility
type SimpleGrpcServerServicesServer interface {
	//Check if 'gRPC-server' is alive with this service
	AreYouAlive(context.Context, *EmptyParameter) (*AckNackResponse, error)
	mustEmbedUnimplementedSimpleGrpcServerServicesServer()
}

// UnimplementedSimpleGrpcServerServicesServer must be embedded to have forward compatible implementations.
type UnimplementedSimpleGrpcServerServicesServer struct {
}

func (UnimplementedSimpleGrpcServerServicesServer) AreYouAlive(context.Context, *EmptyParameter) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AreYouAlive not implemented")
}
func (UnimplementedSimpleGrpcServerServicesServer) mustEmbedUnimplementedSimpleGrpcServerServicesServer() {
}

// UnsafeSimpleGrpcServerServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleGrpcServerServicesServer will
// result in compilation errors.
type UnsafeSimpleGrpcServerServicesServer interface {
	mustEmbedUnimplementedSimpleGrpcServerServicesServer()
}

func RegisterSimpleGrpcServerServicesServer(s grpc.ServiceRegistrar, srv SimpleGrpcServerServicesServer) {
	s.RegisterService(&SimpleGrpcServerServices_ServiceDesc, srv)
}

func _SimpleGrpcServerServices_AreYouAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleGrpcServerServicesServer).AreYouAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpleGrpcServer.SimpleGrpcServerServices/AreYouAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleGrpcServerServicesServer).AreYouAlive(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

// SimpleGrpcServerServices_ServiceDesc is the grpc.ServiceDesc for SimpleGrpcServerServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleGrpcServerServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simpleGrpcServer.SimpleGrpcServerServices",
	HandlerType: (*SimpleGrpcServerServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AreYouAlive",
			Handler:    _SimpleGrpcServerServices_AreYouAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simpleGrpcServer/simpleGrpcServer.proto",
}
